export const HYDRATE_TODO_LIST = "TODO_LIST";
export const TODO_LIST_LOADING = "TODO_LIST_LOADING";
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS";
export const TODO_LIST_FORM_CHANGE = "TODO_LIST_FORM_CHANGE";
export const TODO_LIST_FORM_SUBMIT = "TODO_LIST_FORM_SUBMIT";
export const TODO_LIST_FORM_SUCCESS = "TODO_LIST_FORM_SUCCESS";
export const TODO_LIST_FORM_REDIRECT_INIT = "TODO_LIST_FORM_REDIRECT_INIT";